version: '3'
services:
  liveqso:
    build:
      dockerfile: ./Dockerfile
    container_name: liveqso
    ports:
      - 8098:8000	# Exposed port - see WEBPORT above
    volumes:
      - ./config.js:/usr/src/app/config.js:U
    restart: unless-stopped
