version: '3'
services:
  liveqso:
    build: https://github.com/int2001/wavelog_stream.git#dev
    container_name: liveqso
    ports:
      - 8000:8000
    volumes:
      - ./config.js:/usr/src/app/config.js:U
    restart: unless-stopped
